
services:
  - type: web
    name: mysite
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py makemigrations
      python manage.py migrate
    startCommand: gunicorn mysite.wsgi:application
   
