# Generated by Django 4.0.3 on 2022-03-26 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_train'),
        ('customer', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='station',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manager.station'),
        ),
    ]
