# Generated by Django 4.0.3 on 2022-03-29 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_station_orders_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 17, 29, 3, 610693)),
        ),
    ]
