# Generated by Django 4.0.3 on 2023-04-08 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_orders_food_item_alter_orders_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 9, 55, 13, 623597)),
        ),
    ]
