# Generated by Django 4.0.3 on 2022-03-28 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0005_remove_train_stations_train_stations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.station')),
            ],
        ),
    ]
