# Generated by Django 4.0.3 on 2023-04-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='f_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
