# Generated by Django 4.0.3 on 2022-03-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
