# Generated by Django 4.0.3 on 2022-03-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_station_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stations', models.ManyToManyField(related_name='list_of_stations', to='manager.station')),
            ],
        ),
    ]
