# Generated by Django 4.0.3 on 2022-03-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='stations',
        ),
        migrations.AddField(
            model_name='train',
            name='stations',
            field=models.CharField(default='', max_length=200),
        ),
    ]
